version: "3.1"
services:
  order:
    build: .
    container_name: order-service
    environment:
      PORT: "${PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DATABASE_URL: "${DATABASE_URL}"
    ports:
      - "4100:4100"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
networks:
  default:
    external:
      name: E-commerce_Api
